# Generated by Django 5.2.6 on 2025-09-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('desc', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'NEW'), ('in_proccess', 'IN PROCCESS'), ('finished', 'FINISHED')], max_length=50)),
            ],
            options={
                'verbose_name': 'ToDo',
                'verbose_name_plural': 'ToDo',
            },
        ),
    ]
